spring.application.name=examify-backend
spring.profiles.active=local
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cloudinary (Sẽ dùng để lưu trữ ảnh/file)
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Gemini AI
gemini.api-keys=${GEMINI_API_KEYS}