spring.application.name=examify-backend
server.port=8080

# Chế độ profile (Mặc định là prod trên server, bạn sẽ set local ở máy mình)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:examify}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Gemini AI
gemini.api-keys=${GEMINI_API_KEYS}